### ISSUE TITLE
[Bug]: latest version reloads resources when joining the server.

### ISSUE THREAD

**Issue by MacatMovie** [PlatinPython/ParticleGenerator#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Minecraft Version

1.20.1

### Mod Version

1.2.0.1

### Description

I've updated the mod in the custom modpack and it when I joined the server, it would bring up the Mojang logo loading screen and looking at the log files it seems to reload all the resources. Not a big problem, but still an annoyance, but it is easily solved by downgrading to 1.1.0.0

### Steps to reproduce

Update to latest 1.2.0.1 VGXGen mod and join the server.

**Comment by PlatinPython** [comment]
This is not a bug. Since 1.2.0.0, users can define their own particles, which will need to get loaded onto the particle texture atlas. Therefore a resource reload is necessary.
It also reloads even if you haven't added any custom particles, because the built-in particles now also use that system, so users can disable them if they want to.
There probably are different ways of loading the textures that wouldn't require a full resource reload, but the ideas I've come up either had performance impacts or were just more error prone, so this is the current best solution.
That said, I'm always open to suggestions on how to improve this.

**Comment by MacatMovie** [comment]
Thanks for the clarification. It all makes sense. I just thought about this being the reason the second after I posted it as an issue.
I'll still keep it on the previous version then, since I have a large modpack where server members already complain enough about the loading/server login times 😅 Love the mod though, used it in many builds! 🙏
